# Generated by Django 5.0.2 on 2024-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=255),
        ),
    ]
